[profile.default]
solc_version = '0.8.23'
src = "contracts"
out = "out"
libs = ["lib"]
build_info = true
extra_output = ["storageLayout"]
optimizer = true
optimizer_runs = 8

[fuzz]
runs = 1000

[rpc_endpoints]
bsc = "https://bnb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
bsc-testnet = "https://bnb-testnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[profile.rpc_storage_caching]
chains = "all"
endpoints = "all"

[etherscan]
bsc = { key = "${BSCSCAN_API_KEY}", chain = 56 }  # BSC Mainnet chain ID
bsc-testnet = { key = "${BSCSCAN_API_KEY}", chain = 97 }  # BSC Testnet chain ID